/* Generated By:JavaCC: Do not edit this line. SQLGeneratorConstants.java */
package compilation_project;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLGeneratorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TABLE = 5;
  /** RegularExpression Id. */
  int COLON = 6;
  /** RegularExpression Id. */
  int LPAREN = 7;
  /** RegularExpression Id. */
  int RPAREN = 8;
  /** RegularExpression Id. */
  int COMMA = 9;
  /** RegularExpression Id. */
  int DASH = 10;
  /** RegularExpression Id. */
  int INTEGER_TYPE = 11;
  /** RegularExpression Id. */
  int TEXT_TYPE = 12;
  /** RegularExpression Id. */
  int DATE_TYPE = 13;
  /** RegularExpression Id. */
  int PRIMARY_KEY = 14;
  /** RegularExpression Id. */
  int AUTO = 15;
  /** RegularExpression Id. */
  int REQUIRED = 16;
  /** RegularExpression Id. */
  int UNIQUE = 17;
  /** RegularExpression Id. */
  int DEFAULT_VALUE = 18;
  /** RegularExpression Id. */
  int REFERENCE = 19;
  /** RegularExpression Id. */
  int IDENTIFIER = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"table\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"-\"",
    "\"entier\"",
    "\"texte\"",
    "\"date\"",
    "<PRIMARY_KEY>",
    "\"auto\"",
    "\"requis\"",
    "\"unique\"",
    "<DEFAULT_VALUE>",
    "<REFERENCE>",
    "<IDENTIFIER>",
  };

}
